import * as flsFunctions from "./modules/functionsWebP.js";
import { selectCustom } from "./selectCustom.js";
import { burger } from "./burger.js";
import { introSwiper } from "./introSwiper.js";
import { specialOffersSwiper } from "./specialOffersSwiper.js";
import { specialOffersOpen } from "./specialOffersOpen.js";
import { topCategorySwiper } from "./topCategorySwiper.js";
import { catalogNouislider } from "./catalogNouislider.js";
import { catalogSwiper } from "./catalogSwiper.js";
import { cardsProductsSwiper } from "./cardsProductsSwiper.js";
import { contactsMap } from "./contactsMap.js";

flsFunctions.isWeb();
selectCustom();
burger();
introSwiper();
specialOffersSwiper();
specialOffersOpen();
topCategorySwiper();
catalogNouislider();
catalogSwiper();
cardsProductsSwiper();
contactsMap();
